"""Added UniqueConstraint to Release

Revision ID: 08e996888d77
Revises: b6228e08cbac
Create Date: 2020-05-27 00:03:55.282905

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '08e996888d77'
down_revision = 'b6228e08cbac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_track_name', 'tracks', ['artist_id', 'release_id', 'name'])
    op.alter_column('users', 'created_on',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_on',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('unique_track_name', 'tracks', type_='unique')
    # ### end Alembic commands ###
