"""Added auth_id to User

Revision ID: 1dbb379d8565
Revises: e67449950327
Create Date: 2020-05-22 22:34:00.644830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dbb379d8565'
down_revision = 'e67449950327'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auth_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'auth_id')
    # ### end Alembic commands ###
