"""Added smart contract address to Release

Revision ID: 3c2f57ee81f1
Revises: 08e996888d77
Create Date: 2020-06-02 22:12:34.994262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c2f57ee81f1'
down_revision = '08e996888d77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('releases', sa.Column('smart_contract_address', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'releases', ['smart_contract_address'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'releases', type_='unique')
    op.drop_column('releases', 'smart_contract_address')
    # ### end Alembic commands ###
