"""Added Instagram url to Artist

Revision ID: 5a84a5912821
Revises: 955f693f7a1b
Create Date: 2020-09-30 22:46:39.660385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a84a5912821'
down_revision = '955f693f7a1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('instagram_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'instagram_url')
    # ### end Alembic commands ###
