"""facebook url for artist

Revision ID: 955f693f7a1b
Revises: fab086bca9e0
Create Date: 2020-09-16 21:31:00.500868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '955f693f7a1b'
down_revision = 'fab086bca9e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('facebook_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'facebook_url')
    # ### end Alembic commands ###
