"""Initial migration.

Revision ID: acbb8acbde7d
Revises: 
Create Date: 2020-05-11 21:42:59.709528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acbb8acbde7d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('releases', sa.Column('artist_id', sa.Integer(), nullable=True))
    op.drop_constraint('releases_artist_fkey', 'releases', type_='foreignkey')
    op.create_foreign_key(None, 'releases', 'artists', ['artist_id'], ['id'])
    op.drop_column('releases', 'artist')
    op.add_column('tracks', sa.Column('artist_id', sa.Integer(), nullable=True))
    op.add_column('tracks', sa.Column('release_id', sa.Integer(), nullable=True))
    op.drop_constraint('tracks_artist_fkey', 'tracks', type_='foreignkey')
    op.drop_constraint('tracks_release_fkey', 'tracks', type_='foreignkey')
    op.create_foreign_key(None, 'tracks', 'artists', ['artist_id'], ['id'])
    op.create_foreign_key(None, 'tracks', 'releases', ['release_id'], ['id'])
    op.drop_column('tracks', 'release')
    op.drop_column('tracks', 'artist')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('artist', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tracks', sa.Column('release', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tracks', type_='foreignkey')
    op.drop_constraint(None, 'tracks', type_='foreignkey')
    op.create_foreign_key('tracks_release_fkey', 'tracks', 'releases', ['release'], ['id'])
    op.create_foreign_key('tracks_artist_fkey', 'tracks', 'artists', ['artist'], ['id'])
    op.drop_column('tracks', 'release_id')
    op.drop_column('tracks', 'artist_id')
    op.add_column('releases', sa.Column('artist', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'releases', type_='foreignkey')
    op.create_foreign_key('releases_artist_fkey', 'releases', 'artists', ['artist'], ['id'])
    op.drop_column('releases', 'artist_id')
    # ### end Alembic commands ###
