"""Added artist picture

Revision ID: c21cfe512f8b
Revises: 
Create Date: 2020-06-29 22:49:19.388646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c21cfe512f8b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('artist_picture', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('artists', 'artist_picture')
    # ### end Alembic commands ###
