"""added is_removed to release

Revision ID: e653d5705c6c
Revises: ff724e6b36d9
Create Date: 2020-12-28 23:24:23.547223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e653d5705c6c'
down_revision = 'ff724e6b36d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('releases', sa.Column('is_removed', sa.Boolean(), nullable=True))
    op.execute("UPDATE releases SET is_removed = false")
    op.alter_column('releases', 'is_removed', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('releases', 'is_removed')
    # ### end Alembic commands ###
