"""Added user.

Revision ID: e67449950327
Revises: 
Create Date: 2020-05-19 22:55:14.676709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e67449950327'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('artists_user_fkey', 'artists', type_='foreignkey')
    op.drop_column('artists', 'user')
    op.add_column('users', sa.Column('artist_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'artists', ['artist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'artist_id')
    op.add_column('artists', sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('artists_user_fkey', 'artists', 'users', ['user'], ['id'])
    # ### end Alembic commands ###
