"""Remove PaymentToken

Revision ID: e966eecd6d10
Revises: e653d5705c6c
Create Date: 2021-08-13 23:45:55.719833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e966eecd6d10'
down_revision = 'e653d5705c6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_token',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('smart_contract_address', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ticker', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='payment_token_pkey'),
    sa.UniqueConstraint('smart_contract_address', name='payment_token_smart_contract_address_key')
    )
    # ### end Alembic commands ###
