"""Add artist wallet address

Revision ID: ff724e6b36d9
Revises: c2bc164d0809
Create Date: 2020-11-21 11:50:15.258151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff724e6b36d9'
down_revision = 'c2bc164d0809'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artist_token')
    op.add_column('artists', sa.Column('wallet_address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'wallet_address')
    op.create_table('artist_token',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('smart_contract_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='artist_token_pkey'),
    sa.UniqueConstraint('smart_contract_address', name='artist_token_smart_contract_address_key')
    )
    # ### end Alembic commands ###
